const REMOVE = 'REMOVE';
const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';
const ADDTOCART = 'ADDTOCART';
const CLEARCART = 'CLEARCART';

export { REMOVE, INCREASE, DECREASE, ADDTOCART, CLEARCART };
